name = "Russian Language Pack"
version = "4.3c3"
local desc = {
	en = "Russian localization of the game compiled from the user-suggested translations. The best translations are chosen via user voting. \n\nVersion: "..version,
	ru = "\nРусификация игры, собранная на основе\nголосований за переводы реплик.\nВерсия: "..version}
description = language and desc[language] or desc["en"]
author = "Some1"
forumthread = "/files/file/879-russian-language-pack/"
api_version = 10
icon_atlas = "modicon.xml"
icon = "modicon.tex"
priority = 1
dont_starve_compatible = true
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
server_filter_tags = {"russian"}
